" Name:         Alabaster
" Description:  A light color scheme with minimal amount of highlighting
" Author:       Ilya Bogdanov <fumlead@gmail.com>
" Maintainer:   Ilya Bogdanov <fumlead@gmail.com>
" Website:      https://github.com/vitvakatu/alabaster
" License:      MIT
" Last Updated: Mon May 27 22:55:53 2024

" Generated by Colortemplate v2.2.3

set background=light

hi clear
let g:colors_name = 'alabaster'

let s:t_Co = has('gui_running') ? -1 : get(g:, 'alabaster_t_Co', get(g:, 't_Co', exists('&t_Co') ? +&t_Co : 0))
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link Added diffAdded
hi! link Boolean Constant
hi! link Changed diffChanged
hi! link Character Constant
hi! link Conditional Statement
hi! link CurSearch IncSearch
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link Number Constant
hi! link Operator Statement
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Removed diffRemoved
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link debugBreakpoint SignColumn
hi! link debugPC SignColumn
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#aa3731', '#448c27', '#ffbc05', '#325cc0', '#7a3e9d', '#00ffff', '#f7f7f7', '#707070', '#ff6400', '#64ff00', '#ffff64', '#0064ff', '#ff64ff', '#64ffff', '#ffffff']
endif
if has('nvim')
  let g:terminal_color_0 = '#000000'
  let g:terminal_color_1 = '#aa3731'
  let g:terminal_color_2 = '#448c27'
  let g:terminal_color_3 = '#ffbc05'
  let g:terminal_color_4 = '#325cc0'
  let g:terminal_color_5 = '#7a3e9d'
  let g:terminal_color_6 = '#00ffff'
  let g:terminal_color_7 = '#f7f7f7'
  let g:terminal_color_8 = '#707070'
  let g:terminal_color_9 = '#ff6400'
  let g:terminal_color_10 = '#64ff00'
  let g:terminal_color_11 = '#ffff64'
  let g:terminal_color_12 = '#0064ff'
  let g:terminal_color_13 = '#ff64ff'
  let g:terminal_color_14 = '#64ffff'
  let g:terminal_color_15 = '#ffffff'
endif
if get(g:, 'alabaster_transp_bg', 0) && !has('gui_running')
  hi Normal guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#000000 guibg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
  hi Terminal guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
endif
hi ColorColumn guifg=#000000 guibg=#f0f0f0 gui=NONE cterm=NONE
hi Conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
hi Cursor guifg=#000000 guibg=#007acc gui=NONE cterm=NONE
hi CursorIM guifg=#000000 guibg=#007acc gui=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#f0f0f0 gui=NONE cterm=NONE
hi CursorLine guifg=NONE guibg=#f0f0f0 gui=NONE cterm=NONE
hi CursorLineNr guifg=#007acc guibg=#f7f7f7 gui=NONE cterm=NONE
hi DiffAdd guifg=#6abf40 guibg=#f7f7f7 gui=NONE cterm=NONE
hi DiffChange guifg=#ec8013 guibg=#f7f7f7 gui=NONE cterm=NONE
hi DiffDelete guifg=#d2322d guibg=#f7f7f7 gui=NONE cterm=NONE
hi DiffText guifg=#ec8013 guibg=#f7f7f7 gui=bold cterm=bold
hi Directory guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi EndOfBuffer guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi ErrorMsg guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi FoldColumn guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi Folded guifg=#000000 guibg=#f7f7f7 gui=italic cterm=italic
hi IncSearch guifg=#000000 guibg=#ffbc05 gui=NONE cterm=NONE
hi Substitute guifg=#000000 guibg=#ffbc05 gui=NONE cterm=NONE
hi LineNr guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi MatchParen guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi ModeMsg guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi MoreMsg guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi NonText guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi Pmenu guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi PmenuSbar guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi PmenuSel guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi PmenuThumb guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi Question guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi Search guifg=#000000 guibg=#ffbc05 gui=NONE cterm=NONE
hi SignColumn guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi SpecialKey guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi SpellBad guifg=#000000 guibg=#f7f7f7 guisp=#aa3731 gui=NONE cterm=NONE
hi SpellCap guifg=#000000 guibg=#f7f7f7 guisp=#325cc0 gui=NONE cterm=NONE
hi SpellLocal guifg=#000000 guibg=#f7f7f7 guisp=#7a3e9d gui=NONE cterm=NONE
hi SpellRare guifg=#000000 guibg=#f7f7f7 guisp=#00ffff gui=NONE cterm=NONE
hi StatusLine guifg=#f7f7f7 guibg=#707070 gui=NONE cterm=NONE
hi StatusLineNC guifg=#f7f7f7 guibg=#a5a5a5 gui=NONE cterm=NONE
hi TabLine guifg=#f7f7f7 guibg=#a5a5a5 gui=NONE cterm=NONE
hi TabLineFill guifg=#f7f7f7 guibg=#f7f7f7 gui=NONE cterm=NONE
hi TabLineSel guifg=#f7f7f7 guibg=#707070 gui=NONE cterm=NONE
hi Title guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi VertSplit guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi Visual guifg=#000000 guibg=#bfdbfe gui=NONE cterm=NONE
hi VisualNOS guifg=#000000 guibg=#e0e0e0 gui=NONE cterm=NONE
hi WarningMsg guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi WildMenu guifg=#000000 guibg=#f7f7f7 gui=NONE cterm=NONE
hi Comment guifg=#aa3731 guibg=NONE gui=NONE cterm=NONE
hi Constant guifg=#7a3e9d guibg=NONE gui=NONE cterm=NONE
hi String guifg=#448c27 guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#aa3731 guibg=NONE gui=NONE cterm=NONE
hi Identifier guifg=#000000 guibg=NONE gui=NONE cterm=NONE
hi Ignore guifg=#000000 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#000000 guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#000000 guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#000000 guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#000000 guibg=NONE gui=NONE cterm=NONE
hi Type guifg=#000000 guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=#000000 guibg=NONE gui=NONE cterm=NONE
hi WinSeparator guifg=NONE guibg=#707070 gui=NONE cterm=NONE
hi ToolbarLine guifg=NONE guibg=#f7f7f7 gui=NONE cterm=NONE
hi ToolbarButton guifg=#000000 guibg=#f7f7f7 gui=bold cterm=bold
if !s:italics
  hi Folded gui=NONE cterm=NONE
endif
let g:guicursor='n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20'

if s:t_Co >= 256
  if get(g:, 'alabaster_transp_bg', 0)
    hi Normal ctermfg=16 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=16 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=16 ctermbg=231 cterm=NONE
    hi Terminal ctermfg=16 ctermbg=231 cterm=NONE
  endif
  hi ColorColumn ctermfg=16 ctermbg=255 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=16 ctermbg=32 cterm=NONE
  hi CursorIM ctermfg=16 ctermbg=32 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorLineNr ctermfg=32 ctermbg=231 cterm=NONE
  hi DiffAdd ctermfg=70 ctermbg=231 cterm=NONE
  hi DiffChange ctermfg=208 ctermbg=231 cterm=NONE
  hi DiffDelete ctermfg=160 ctermbg=231 cterm=NONE
  hi DiffText ctermfg=208 ctermbg=231 cterm=bold
  hi Directory ctermfg=16 ctermbg=231 cterm=NONE
  hi EndOfBuffer ctermfg=16 ctermbg=231 cterm=NONE
  hi ErrorMsg ctermfg=16 ctermbg=231 cterm=NONE
  hi FoldColumn ctermfg=16 ctermbg=231 cterm=NONE
  hi Folded ctermfg=16 ctermbg=231 cterm=italic
  hi IncSearch ctermfg=16 ctermbg=214 cterm=NONE
  hi Substitute ctermfg=16 ctermbg=214 cterm=NONE
  hi LineNr ctermfg=16 ctermbg=231 cterm=NONE
  hi MatchParen ctermfg=16 ctermbg=231 cterm=NONE
  hi ModeMsg ctermfg=16 ctermbg=231 cterm=NONE
  hi MoreMsg ctermfg=16 ctermbg=231 cterm=NONE
  hi NonText ctermfg=16 ctermbg=231 cterm=NONE
  hi Pmenu ctermfg=16 ctermbg=231 cterm=NONE
  hi PmenuSbar ctermfg=16 ctermbg=231 cterm=NONE
  hi PmenuSel ctermfg=16 ctermbg=231 cterm=NONE
  hi PmenuThumb ctermfg=16 ctermbg=231 cterm=NONE
  hi Question ctermfg=16 ctermbg=231 cterm=NONE
  hi Search ctermfg=16 ctermbg=214 cterm=NONE
  hi SignColumn ctermfg=16 ctermbg=231 cterm=NONE
  hi SpecialKey ctermfg=16 ctermbg=231 cterm=NONE
  hi SpellBad ctermfg=16 ctermbg=231 cterm=NONE
  hi SpellCap ctermfg=16 ctermbg=231 cterm=NONE
  hi SpellLocal ctermfg=16 ctermbg=231 cterm=NONE
  hi SpellRare ctermfg=16 ctermbg=231 cterm=NONE
  hi StatusLine ctermfg=231 ctermbg=242 cterm=NONE
  hi StatusLineNC ctermfg=231 ctermbg=248 cterm=NONE
  hi TabLine ctermfg=231 ctermbg=248 cterm=NONE
  hi TabLineFill ctermfg=231 ctermbg=231 cterm=NONE
  hi TabLineSel ctermfg=231 ctermbg=242 cterm=NONE
  hi Title ctermfg=16 ctermbg=231 cterm=NONE
  hi VertSplit ctermfg=16 ctermbg=231 cterm=NONE
  hi Visual ctermfg=16 ctermbg=153 cterm=NONE
  hi VisualNOS ctermfg=16 ctermbg=254 cterm=NONE
  hi WarningMsg ctermfg=16 ctermbg=231 cterm=NONE
  hi WildMenu ctermfg=16 ctermbg=231 cterm=NONE
  hi Comment ctermfg=124 ctermbg=NONE cterm=NONE
  hi Constant ctermfg=91 ctermbg=NONE cterm=NONE
  hi String ctermfg=28 ctermbg=NONE cterm=NONE
  hi Error ctermfg=124 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=16 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=16 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=16 ctermbg=NONE cterm=NONE
  hi Special ctermfg=16 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=16 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=16 ctermbg=NONE cterm=NONE
  hi Type ctermfg=16 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=16 ctermbg=NONE cterm=NONE
  hi WinSeparator ctermfg=NONE ctermbg=242 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=231 cterm=NONE
  hi ToolbarButton ctermfg=16 ctermbg=231 cterm=bold
  if !s:italics
    hi Folded cterm=NONE
  endif
  let g:guicursor='n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20'
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'alabaster_transp_bg', 0)
    hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Black ctermbg=LightGrey cterm=NONE
    hi Terminal ctermfg=Black ctermbg=LightGrey cterm=NONE
  endif
  hi ColorColumn ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=Black ctermbg=DarkBlue cterm=NONE
  hi CursorIM ctermfg=Black ctermbg=DarkBlue cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi CursorLineNr ctermfg=DarkBlue ctermbg=LightGrey cterm=NONE
  hi DiffAdd ctermfg=LightGreen ctermbg=LightGrey cterm=NONE
  hi DiffChange ctermfg=DarkYellow ctermbg=LightGrey cterm=NONE
  hi DiffDelete ctermfg=LightRed ctermbg=LightGrey cterm=NONE
  hi DiffText ctermfg=DarkYellow ctermbg=LightGrey cterm=bold
  hi Directory ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi EndOfBuffer ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi ErrorMsg ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi FoldColumn ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Folded ctermfg=Black ctermbg=LightGrey cterm=italic
  hi IncSearch ctermfg=Black ctermbg=DarkYellow cterm=NONE
  hi Substitute ctermfg=Black ctermbg=DarkYellow cterm=NONE
  hi LineNr ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi MatchParen ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi ModeMsg ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi MoreMsg ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi NonText ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuSbar ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi PmenuThumb ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Question ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Search ctermfg=Black ctermbg=DarkYellow cterm=NONE
  hi SignColumn ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi SpecialKey ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi SpellBad ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi SpellCap ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi SpellLocal ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi SpellRare ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi StatusLine ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi StatusLineNC ctermfg=LightGrey ctermbg=LightGrey cterm=NONE
  hi TabLine ctermfg=LightGrey ctermbg=LightGrey cterm=NONE
  hi TabLineFill ctermfg=LightGrey ctermbg=LightGrey cterm=NONE
  hi TabLineSel ctermfg=LightGrey ctermbg=DarkGrey cterm=NONE
  hi Title ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi VertSplit ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Visual ctermfg=Black ctermbg=LightBlue cterm=NONE
  hi VisualNOS ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi WarningMsg ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi Comment ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Constant ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi String ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Black ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=Black ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Black ctermbg=NONE cterm=NONE
  hi Special ctermfg=Black ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Black ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Black ctermbg=NONE cterm=NONE
  hi Type ctermfg=Black ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Black ctermbg=NONE cterm=NONE
  hi WinSeparator ctermfg=NONE ctermbg=DarkGrey cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=LightGrey cterm=NONE
  hi ToolbarButton ctermfg=Black ctermbg=LightGrey cterm=bold
  if !s:italics
    hi Folded cterm=NONE
  endif
  let g:guicursor='n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20'
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: light
" Color: black         #000000                   ~         Black
" Color: white         #f7f7f7                   ~         LightGrey
" Color: lineHighlight #f0f0f0                   ~         LightGrey
" Color: active        #007ACC                   ~         DarkBlue
" Color: selection     #BFDBFE                   ~         LightBlue
" Color: selectionInactive #E0E0E0 ~ LightGrey
" Color: diffAdd #6ABF40 ~ LightGreen
" Color: diffChange #EC8013 ~ DarkYellow
" Color: diffDelete #D2322D ~ LightRed
" Color: blue      #325CC0 ~ DarkBlue
" Color: green     #448C27 ~ DarkGreen
" Color: red       #AA3731 ~ DarkRed
" Color: magenta   #7A3E9D ~ DarkMagenta
" Color: grey      #707070 ~ DarkGrey
" Color: lightGrey      #A5A5A5 ~ LightGrey
" Color: orange    #FFBC05 ~ DarkYellow
" Color: cyan          rgb(  0, 255, 255)        ~         DarkCyan
" Color: brightred     rgb(255, 100,   0)        ~         LightRed
" Color: brightgreen   rgb(100, 255,   0)        ~         LightGreen
" Color: brightyellow  rgb(255, 255, 100)        ~         LightYellow
" Color: brightblue    rgb(  0, 100, 255)        ~         LightBlue
" Color: brightmagenta rgb(255, 100, 255)        ~         LightMagenta
" Color: brightcyan    rgb(100, 255, 255)        ~         LightCyan
" Color: brightwhite   #ffffff                  231        White
" Term colors: black red green orange blue magenta cyan white
" Term colors: grey brightred brightgreen brightyellow
" Term colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=8 sw=2 sts=2
